// =====================================================
// app.js — Stable Version + Dynamic Report Detection
// Leaflet + GeoJSON + USI
// =====================================================

const GEOJSON_FILE = "usi_cities_2025Q4v1.geojson";
const ACTIVE_REPORTS_FILE = "active-cities.json";

let activeReports = new Set();

// -----------------------------------------------------
// 0) Load active report list (generated by notebook)
// -----------------------------------------------------
fetch(ACTIVE_REPORTS_FILE)
  .then(res => res.json())
  .then(data => {
    activeReports = new Set(data);
    console.log("Loaded active reports:", activeReports);
  })
  .catch(err => {
    console.warn("active-cities.json not found or failed to load.");
  });

// -----------------------------------------------------
// 1) Interaction guard
// -----------------------------------------------------
function hardenMapInteractivity() {
  const el = document.getElementById("map");
  if (!el) return;

  el.style.position = el.style.position || "fixed";
  el.style.zIndex = "900";
  el.style.pointerEvents = "auto";
  document.body.style.pointerEvents = "auto";
}

hardenMapInteractivity();

// -----------------------------------------------------
// 2) Create map
// -----------------------------------------------------
const map = L.map("map", {
  worldCopyJump: false,
  zoomControl: true
}).setView([20, 0], 2);

const hardBounds = [[-85, -180],[85, 180]];
map.setMaxBounds(hardBounds);
map.options.maxBoundsViscosity = 1.0;

L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
  maxZoom: 19,
  noWrap: true,
  attribution: "&copy; OpenStreetMap contributors"
}).addTo(map);

// -----------------------------------------------------
// 3) Helpers
// -----------------------------------------------------
function toNumber(x) {
  const n = Number(x);
  return Number.isFinite(n) ? n : null;
}

function keepDecimals(x) {
  if (x === undefined || x === null || x === "") return "N/A";
  return String(x);
}

function fmtIncome(n) {
  if (n === null) return "N/A";
  return n.toLocaleString(undefined, { maximumFractionDigits: 0 });
}

function slugify(str) {
  return String(str)
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^\w\-]+/g, "");
}

function usiRating(u) {
  if (u === null) return "Unknown";
  if (u < 30) return "Comfortable";
  if (u < 35) return "Stretched";
  if (u < 40) return "High burden";
  if (u < 45) return "Severe burden";
  if (u < 55) return "Unaffordable";
  return "Extreme";
}

function getColor(u) {
  if (u === null) return "#999";
  if (u < 30) return "#2ecc71";
  if (u < 35) return "#f1c40f";
  if (u < 40) return "#e67e22";
  if (u < 45) return "#e74c3c";
  if (u < 55) return "#6c3483";
  return "#3b1f4a";
}

function getRadius(u) {
  if (u === null) return 10;
  const minR = 8, maxR = 18;
  return minR + (maxR - minR) * (u / 100);
}

// -----------------------------------------------------
// 4) Key Detection (Old Naming Retained)
// -----------------------------------------------------
const KEY_CANDIDATES = {
  usi: ["usi"],
  city: ["city"],
  country: ["country"],
  housingPct: ["rental_index"],
  foodPct: ["engels_index"],
  rentMonthly: ["monthly_rent_1br"],
  foodMonthly: ["monthly_food"],
  incomeMonthly: ["average_monthly_salary"]
};

function pickFirstKey(obj, candidates) {
  for (const k of candidates) {
    if (obj[k] !== undefined) return k;
  }
  return null;
}

// -----------------------------------------------------
// 5) Popup Builder (Dynamic Report Link)
// -----------------------------------------------------
function buildPopup(p, keys) {

  const usi = keys.usiKey ? toNumber(p[keys.usiKey]) : null;
  const city = p[keys.cityKey] || "Unknown";
  const countryRaw = p[keys.countryKey] || "";
  const country = countryRaw ? `, ${countryRaw}` : "";

  const housing = keys.housingPctKey ? toNumber(p[keys.housingPctKey]) : null;
  const food = keys.foodPctKey ? toNumber(p[keys.foodPctKey]) : null;
  const income = keys.incomeMonthlyKey ? toNumber(p[keys.incomeMonthlyKey]) : null;

  const housingDisplay = keepDecimals(housing);
  const foodDisplay = keepDecimals(food);
  const usiDisplay = keepDecimals(usi);
  const rating = usiRating(usi);

  const citySlug = slugify(city);
  const countrySlug = slugify(countryRaw);

  // Full expected path from notebook JSON
  const reportPath = `/cities/${countrySlug}/${citySlug}.html`;

  let reportLink = "";
  if (activeReports.has(reportPath)) {
    reportLink = `
      <div style="margin-top:12px;">
        <a href="${reportPath}" target="_blank">
          See full city report →
        </a>
      </div>
    `;
  }

  return `
    <div style="min-width: 180px; font-family: system-ui; font-size: 13px; line-height: 1.4;">
      <b>${city}${country}</b>

      <div style="margin-top: 8px;">
        USI: ${usiDisplay} (${rating})
      </div>

      <div style="margin-top: 8px;">
        <b>Housing:</b> ${housingDisplay}
      </div>

      <div>
        <b>Food:</b> ${foodDisplay}
      </div>

      <div style="margin-top:12px;">
        <b>Typical Income</b><br>
        <span style="opacity:0.65;">(local currency, monthly)</span>
        ${fmtIncome(income)}
      </div>

      ${reportLink}

      <div style="margin-top:8px;">
        <a href="calculator.html?income=${income || 0}&housingPct=${housing || 0}&foodPct=${food || 0}" target="_blank">
          How much would I have left? →
        </a>
      </div>
    </div>
  `;
}

// -----------------------------------------------------
// 6) Load + Render
// -----------------------------------------------------
fetch(GEOJSON_FILE)
  .then(res => res.json())
  .then(geojson => {

    const firstProps = geojson?.features?.[0]?.properties || {};

    const keys = {
      usiKey: pickFirstKey(firstProps, KEY_CANDIDATES.usi),
      cityKey: pickFirstKey(firstProps, KEY_CANDIDATES.city),
      countryKey: pickFirstKey(firstProps, KEY_CANDIDATES.country),
      housingPctKey: pickFirstKey(firstProps, KEY_CANDIDATES.housingPct),
      foodPctKey: pickFirstKey(firstProps, KEY_CANDIDATES.foodPct),
      rentMonthlyKey: pickFirstKey(firstProps, KEY_CANDIDATES.rentMonthly),
      foodMonthlyKey: pickFirstKey(firstProps, KEY_CANDIDATES.foodMonthly),
      incomeMonthlyKey: pickFirstKey(firstProps, KEY_CANDIDATES.incomeMonthly)
    };

    const layer = L.geoJSON(geojson, {
      pointToLayer: (feature, latlng) => {
        const p = feature.properties || {};
        const u = keys.usiKey ? toNumber(p[keys.usiKey]) : null;
        const c = getColor(u);

        return L.circleMarker(latlng, {
          radius: getRadius(u),
          color: c,
          fillColor: c,
          fillOpacity: 0.78,
          weight: 1
        });
      },
      onEachFeature: (feature, marker) => {
        marker.bindPopup(buildPopup(feature.properties || {}, keys), {
          maxWidth: 340
        });
      }
    }).addTo(map);

    const b = layer.getBounds();
    if (b.isValid()) map.fitBounds(b, { padding: [20, 20] });

    setTimeout(hardenMapInteractivity, 50);
  })
  .catch(err => {
    console.error(err);
    alert("Failed to load city data.");
  });